// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-packages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var packages = [
  {
    id: "club-night",
    tier: "I",
    title: "Club Night",
    price_inr: 12e3,
    unit: "up to 4 hours",
    tagline: "Perfect for a single event, one venue.",
    includes: [
      "One photographer",
      "150+ edited frames",
      "48-hour delivery",
      "Private Google Drive gallery"
    ]
  },
  {
    id: "fest-weekend",
    tier: "II",
    title: "Fest Weekend",
    price_inr: 42e3,
    unit: "3 days \xB7 multi-venue",
    tagline: "Cultural fests, sports weeks, orientation.",
    includes: [
      "Two-photographer crew",
      "600+ edited frames",
      "Same-day social selects",
      "Daily reel-ready dumps",
      "Poster & press-kit exports"
    ],
    badge: "Most booked"
  },
  {
    id: "yearbook",
    tier: "III",
    title: "The Yearbook",
    price_inr: 12e4,
    unit: "full academic year",
    tagline: "Coverage across every major event, term-long.",
    includes: [
      "6\u20138 events / year",
      "Dedicated campus lead",
      "Curated year-end zine (printed)",
      "Archive on custom subdomain",
      "Media training for your club"
    ]
  }
];
var list_packages_default = defineTool({
  name: "list_packages",
  title: "List photography packages",
  description: "Returns Focus \xD7 Campus photography packages, including tier, price in INR, coverage unit, and what's included.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(packages, null, 2) }],
    structuredContent: { packages }
  })
});

// src/lib/mcp/tools/list-event-types.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var eventTypes = [
  { slug: "cultural-fest", label: "Cultural Fest", notes: "Multi-day fest with concerts, competitions, stalls." },
  { slug: "convocation", label: "Convocation / Graduation", notes: "Ceremony, robes, family portraits, stage moments." },
  { slug: "sports-week", label: "Sports Week", notes: "Fast-shutter action, medal ceremonies, team portraits." },
  { slug: "hackathon", label: "Hackathon", notes: "24\u201348 hr coverage, candid maker moments, closing pitches." },
  { slug: "theatre-night", label: "Theatre / Cultural Night", notes: "Low-light stage photography, dress rehearsal + show." },
  { slug: "orientation", label: "Orientation / Freshers", notes: "Icebreakers, group portraits, welcome address." },
  { slug: "conference", label: "Conference / Keynote", notes: "Speakers, audience, sponsor logos, press-ready selects." },
  { slug: "alumni-meet", label: "Alumni Meet", notes: "Reunions, networking mingles, gala dinners." }
];
var list_event_types_default = defineTool2({
  name: "list_event_types",
  title: "List supported event types",
  description: "Returns the campus event types Focus covers, with a short note on what each shoot typically involves.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(eventTypes, null, 2) }],
    structuredContent: { event_types: eventTypes }
  })
});

// src/lib/mcp/tools/list-featured-shoots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var shoots = [
  {
    id: "spandan-24",
    title: "Spandan '24",
    campus: "IIT Bombay",
    event_type: "cultural-fest",
    frames: 812,
    highlights: ["Main stage headliner", "3-day fest", "Reel-ready dumps"]
  },
  {
    id: "convocation-25",
    title: "Convocation 2025",
    campus: "Delhi University",
    event_type: "convocation",
    frames: 430,
    highlights: ["Chief guest address", "Robed portraits", "Family moments"]
  },
  {
    id: "hack-the-north",
    title: "Hack The North",
    campus: "BITS Pilani",
    event_type: "hackathon",
    frames: 604,
    highlights: ["36-hour build", "Sponsor deliverables", "Final pitches"]
  },
  {
    id: "theatre-night-vii",
    title: "Theatre Night VII",
    campus: "St. Stephen's College",
    event_type: "theatre-night",
    frames: 275,
    highlights: ["Dress rehearsal", "Full show", "Backstage documentary"]
  }
];
var list_featured_shoots_default = defineTool3({
  name: "list_featured_shoots",
  title: "List featured shoots",
  description: "Returns a curated list of recent Focus campus shoots with campus, event type, and highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(shoots, null, 2) }],
    structuredContent: { shoots }
  })
});

// src/lib/mcp/tools/get-studio-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var info = {
  name: "Focus",
  tagline: "Event photography for universities and campuses.",
  based_in: "India",
  travels: "Pan-India, with additional travel quoted on request.",
  contact: {
    email: "hello@focus.studio",
    instagram: "@focus.campus"
  },
  turnaround: "Same-day social selects; full gallery in 48 hours.",
  booking_url: "/#booking",
  notes: "Invoiced through your university with a student discount baked in."
};
var get_studio_info_default = defineTool4({
  name: "get_studio_info",
  title: "Get studio info",
  description: "Returns basic contact, turnaround, and booking info for the Focus campus photography studio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
    structuredContent: info
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "focus-campus-mcp",
  title: "Focus \u2014 Campus Event Photography",
  version: "0.1.0",
  instructions: "Tools for the Focus campus event photography studio. Use `list_packages` for pricing tiers, `list_event_types` for the kinds of campus events covered, `list_featured_shoots` for recent work, and `get_studio_info` for contact and turnaround details.",
  tools: [list_packages_default, list_event_types_default, list_featured_shoots_default, get_studio_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
